@startuml "login page"
object Login{
    state
    \t username
    \t password
    \t onSubmit
}
object Input{
    props
    \t value
    \t onChangeText
    \t placeholder
    \t placeholderTextColor
    \t iconSource
    \t containerStyle
    \t iconStyle
    \t activeContainStyle
    state
    \t active
}
Login -->Input
@enduml
